owner: NasteMusic
repo: upptime
sites:
  - name: Dayflow
    url: https://dayflow.life/
  - name: Mythic PBC
    url: https://mythic-pbc.pages.dev/

status-website:
  cname: status.dayflow.life
  name: Dayflow Status
  logoUrl: https://dayflow.life/favicon.ico
